DROP TABLE IF EXISTS bum_kampung;
DROP TABLE IF EXISTS pelaksanaan_documents;
DROP TABLE IF EXISTS subkegiatan_ssd;
DROP TABLE IF EXISTS ssd;
DROP TABLE IF EXISTS subkegiatan;
DROP TABLE IF EXISTS data_wilayah_public_settings;
DROP TABLE IF EXISTS data_wilayah;
DROP TABLE IF EXISTS kab_kota;
DROP TABLE IF EXISTS admin_users;
