WITH source (
  source_no,
  kabupaten_kota,
  distrik,
  kampung,
  nama_bum_kampung,
  kategori,
  status
) AS (
  VALUES
    (1, 'SORONG', 'MAKBON', 'ASBAKEN', 'BUM DESA PERSAMOAS MANDIRI ASBAKEN', 'BUMKam', 'Nama Terverifikasi'),
    (2, 'SORONG', 'MAKBON', 'MALAUMKARTA', 'BUM DESA KAWAK LEN MALAUMKARTA', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (3, 'SORONG', 'MAKBON', 'BATU LUBANG', 'BUM DESA FEIN NEH BATU LUBANG', 'BUMKam', 'Nama Terverifikasi'),
    (4, 'SORONG', 'MAKBON', 'BATU LUBANG PANTAI', 'BUM DESA BAINGGIK JAYA BATU LUBANG PANTAI', 'BUMKam', 'Nama Terverifikasi'),
    (5, 'SORONG', 'MAKBON', 'KWADAS', 'BUM DESA KALABO KWADAS', 'BUMKam', 'Nama Terverifikasi'),
    (6, 'SORONG', 'MAKBON', 'TELUK DORE', 'BUM DESA MALALUWILIN TELUK DORE', 'BUMKam', 'Nama Terverifikasi'),
    (7, 'SORONG', 'MAKBON', 'SAWATUK', 'BUM DESA KALATEVE JAYA SAWATUK', 'BUMKam', 'Nama Terverifikasi'),
    (8, 'SORONG', 'MAKBON', 'KLASIMIGIK', 'BUM DESA WARSAMSUNG KLASIMIGIK', 'BUMKam', 'Nama Terverifikasi'),
    (9, 'SORONG', 'MAKBON', 'KLAGULUS', 'BUM DESA KLASEME KLAMI JAYA KLAGULUS', 'BUMKam', 'Nama Terverifikasi'),
    (10, 'SORONG', 'MAKBON', 'SUATOLO', 'BUM DESA UMSHIGAI SUATOLO', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (11, 'SORONG', 'MAKBON', 'MIBI', 'BUM DESA MAILINNEI MIBI', 'BUMKam', 'Nama Terverifikasi'),
    (12, 'SORONG', 'BERAUR', 'SORAIN', 'BUM DESA RAKYAT BERDIKARI SORAIN', 'BUMKam', 'Nama Terverifikasi'),
    (13, 'SORONG', 'SALAWATI', 'WALAL', 'BUM DESA LESTARI JAYA WALAL', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (14, 'SORONG', 'SALAWATI', 'MALAUS', 'BUM DESA MANDIRI MALAUS', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (15, 'SORONG', 'SEGET', 'KASIMLE', 'BUM DESA PETRA KLAFITI KASIMLE', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (16, 'SORONG', 'AIMAS', 'MAIBO', 'BUM DESA EME YODERE MAIBO', 'BUMKam', 'Nama Terverifikasi'),
    (17, 'SORONG', 'AIMAS', 'AIMO', 'BUM DESA ANU BETA TUBAT AIMO', 'BUMKam', 'Nama Terverifikasi'),
    (18, 'SORONG', 'AIMAS', 'MALASAUM', 'BUM DESA LANFAGU MALASAUM', 'BUMKam', 'Perbaikan Nama'),
    (19, 'SORONG', 'KLAMONO', 'KLAWANA', 'BUM DESA NOLOMPOBOK KLAWANA', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (20, 'SORONG', 'SAYOSA', 'KLAIN', 'BUM DESA MALAUF KLAIN', 'BUMKam', 'Nama Terverifikasi'),
    (21, 'SORONG', 'SEGUN', 'MAJEMAU', 'BUM DESA MEKAR JAYA MAJEMAU', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (22, 'SORONG', 'SEGUN', 'KLAJARING', 'BUM DESA LANMELE KLAJARING', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (23, 'SORONG', 'SEGUN', 'MALAMAS', 'BUM DESA BAIK GARA MALAMAS', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (24, 'SORONG', 'MAYAMUK', 'ARAR', 'BUM DESA ARAR BERDIKARI ARAR', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (25, 'SORONG', 'MAYAMUK', 'KLASMELEK', 'BUM DESA MITRA KARYA KLASMELEK', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (26, 'SORONG', 'MAYAMUK', 'WEN', 'BUM DESA NANIBILI WEN', 'BUMKam', 'Nama Terverifikasi'),
    (27, 'SORONG', 'MAYAMUK', 'ASJIDBA', 'BUM DESA SATU HATI ASJIDBA', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (28, 'SORONG', 'MAYAMUK', 'MALAMAY', 'BUM DESA MAJAF JAYA MALAMAY', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (29, 'SORONG', 'SALAWATI SELATAN', 'DULBATAN', 'BUM DESA FROUNKET DULBATAN', 'BUMKam', 'Nama Terverifikasi'),
    (30, 'SORONG', 'SALAWATI SELATAN', 'MASMAPOP', 'BUM DESA TEMLEFO MASMAPOP', 'BUMKam', 'Nama Terverifikasi'),
    (31, 'SORONG', 'KLABOT', 'KLABOT', 'BUM DESA KAFKOL MANDIRI KLABOT', 'BUMKam', 'Nama Terverifikasi'),
    (32, 'SORONG', 'KLABOT', 'KANOLO', 'BUM DESA KANOLO SEJAHTRA KANOLO', 'BUMKam', 'Nama Terverifikasi'),
    (33, 'SORONG', 'KLABOT', 'WARKTI', 'BUM DESA WARKRO JAYA WARKTI', 'BUMKam', 'Nama Terverifikasi'),
    (34, 'SORONG', 'KLAWAK', 'AYOLOKFLE', 'BUM DESA YADANFLE MANDIRI AYOLOKFLE', 'BUMKam', 'Nama Terverifikasi'),
    (35, 'SORONG', 'KLAWAK', 'TOTJIN', 'BUM DESA WAIN JAYA TOTJIN', 'BUMKam', 'Nama Terverifikasi'),
    (36, 'SORONG', 'KLAYILI', 'MALALILIS', 'BUM DESA TILIGINWES MALALILIS', 'BUMKam', 'Nama Terverifikasi'),
    (37, 'SORONG', 'KLASO', 'MISKUM', 'BUM DESA KAWAK MISKUM', 'BUMKam', 'Nama Terverifikasi'),
    (38, 'SORONG', 'KLASO', 'KLAMUGUN', 'BUM DESA MALASAMUK KLAMUGUN', 'BUMKam', 'Nama Terverifikasi'),
    (39, 'SORONG', 'MOISEGEN', 'KLAFDALIM', 'BUM DESA KURNIA SEJAHTERA KLAFDALIM', 'BUMKam', 'Nama Terverifikasi'),
    (40, 'SORONG', 'MOISEGEN', 'KLAFORO', 'BUM DESA KLAFORO BERSATU KLAFORO', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (41, 'SORONG', 'MOISEGEN', 'KLASARIN', 'BUM DESA PAPUA BOTFLARI KLASARIN', 'BUMKam', 'Nama Terverifikasi'),
    (42, 'SORONG', 'MOISEGEN', 'KLAWOTON', 'BUM DESA MADE''EM KLAWOTON', 'BUMKam', 'Nama Terverifikasi'),
    (43, 'SORONG', 'MOISEGEN', 'MASMILI', 'BUM DESA AGRONAI MASMILI', 'BUMKam', 'Nama Terverifikasi'),
    (44, 'SORONG', 'SORONG', 'MAIBO', 'BUM DESA PAPOLOM MALI PAFI MAIBO', 'BUMKam', 'Nama Terverifikasi'),
    (45, 'SORONG', 'WEMAK', 'SALUK', 'BUM DESA JELAKDI SALUK', 'BUMKam', 'Nama Terverifikasi'),
    (46, 'SORONG', 'WEMAK', 'KLAWREN', 'BUM DESA LINTWOK KLAWREN', 'BUMKam', 'Nama Terverifikasi'),
    (47, 'SORONG', 'WEMAK', 'WOLOIN', 'BUM DESA DOMPLE WOLOIN', 'BUMKam', 'Nama Terverifikasi'),
    (48, 'SORONG', 'WEMAK', 'KLALIN MOS', 'BUM DESA MOSJA KLALIN MOS', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (49, 'SORONG', 'WEMAK', 'KWARI', 'BUM DESA BUNLEF KWARI', 'BUMKam', 'Nama Terverifikasi'),
    (50, 'SORONG', 'WEMAK', 'KAMLIN', 'BUM DESA WEMBUL KAMLIN', 'BUMKam', 'Nama Terverifikasi'),
    (51, 'SORONG', 'SUNOOK', 'BOUWOI', 'BUM DESA BWEM WOITIK BOUWOI', 'BUMKam', 'Nama Terverifikasi'),
    (52, 'SORONG', 'BUK', 'BUK', 'BUM DESA EDVI BUK', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (53, 'SORONG', 'BUK', 'MLAKHAN', 'BUM DESA GUNUNG PERANG MLAKHAN', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (54, 'SORONG', 'BUK', 'KLAIS', 'BUM DESA KIMRIT KLAIS', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (55, 'SORONG', 'BUK', 'MIMPE', 'BUM DESA BERISOPIA MIMPE', 'BUMKam', 'Nama Terverifikasi'),
    (56, 'SORONG', 'BUK', 'TIKLEN', 'BUM DESA SOLKOL TIKLEN', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (57, 'SORONG', 'BUK', 'KLAHEN', 'BUM DESA DYOM BRA KLAHEN', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (58, 'SORONG', 'BUK', 'MOOS', 'BUM DESA MOOS JAYA MOOS', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (59, 'SORONG', 'SAENGKEDUK', 'SAENGKEDUK', 'BUM DESA ULE PE SAENGKEDUK', 'BUMKam', 'Nama Terverifikasi'),
    (60, 'SORONG', 'MALABOTOM', 'MALASIGIT', 'BUM DESA MAJU JAYA MALASIGIT', 'BUMKam', 'Nama Terverifikasi'),
    (61, 'SORONG', 'MALABOTOM', 'MALAJAPA', 'BUM DESA SINIFAGU MALAJAPA', 'BUMKam', 'Nama Terverifikasi'),
    (62, 'SORONG', 'MALABOTOM', 'MAGATARUM', 'BUM DESA MAMBRUK MAGATARUM', 'BUMKam', 'Nama Terverifikasi'),
    (63, 'SORONG', 'MALABOTOM', 'TANAH TINGGI', 'BUM DESA TIRTO NADI TANAH TINGGI', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (64, 'SORONG', 'HOBARD', 'FLOYI', 'BUM DESA MAMI HEHET FLOYI', 'BUMKam', 'Nama Terverifikasi'),
    (65, 'SORONG', 'SALAWATI TENGAH', 'WALIAM', 'BUM DESA WALIAM MANDIRI WALIAM', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (66, 'SORONG', 'SALAWATI TENGAH', 'MARALOL', 'BUM DESA BANDAWAR MANDIRI MARALOL', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (67, 'SORONG', 'SALAWATI TENGAH', 'MEYAUP', 'BUM DESA KARYA MANDIRI MEYAUP', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (68, 'SORONG SELATAN', 'MOSWAREN', 'BUMI AJO', 'BUM DESA TABAM RAIT MOS BUMI AJO', 'BUMKam', 'Nama Terverifikasi'),
    (69, 'RAJA AMPAT', 'MISOOL (MISOOL UTARA)', 'WAIGAMA', 'BUM DESA TABIOOL WAIGAMA', 'BUMKam', 'Nama Terverifikasi'),
    (70, 'RAJA AMPAT', 'MISOOL (MISOOL UTARA)', 'ATKARI', 'BUM DESA SEJAHTERA ATKARI', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (71, 'RAJA AMPAT', 'WAIGEO SELATAN', 'SAONEK', 'BUM DESA WEIM PALE SAONEK', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (72, 'RAJA AMPAT', 'WAIGEO SELATAN', 'YENBESER', 'BUM DESA YAMANDERO YENBESER', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (73, 'RAJA AMPAT', 'WAIGEO SELATAN', 'FRIWEN', 'BUM DESA MARINBEKO FRIWEN', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (74, 'RAJA AMPAT', 'SALAWATI UTARA', 'SAMATE', 'BUM DESA FATANON SAMATE', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (75, 'RAJA AMPAT', 'SALAWATI UTARA', 'JEFMAN BARAT', 'BUM DESA KOFANDUR JEFMAN BARAT', 'BUMKam', 'Nama Terverifikasi'),
    (76, 'RAJA AMPAT', 'SALAWATI UTARA', 'JEFMAN TIMUR', 'BUM DESA TANJUNG BATU JEFMAN TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (77, 'RAJA AMPAT', 'KEPULAUAN AYAU', 'YENKAWIR', 'BUM DESA YENKAWIR INDAH YENKAWIR', 'BUMKam', 'Nama Terverifikasi'),
    (78, 'RAJA AMPAT', 'KEPULAUAN AYAU', 'BOISERAN', 'BUM DESA MANDIRI BOISERAN', 'BUMKam', 'Nama Terverifikasi'),
    (79, 'RAJA AMPAT', 'KEPULAUAN AYAU', 'YENKANFAN', 'BUM DESA YENKANFAN MANDIRI YENKANFAN', 'BUMKam', 'Nama Terverifikasi'),
    (80, 'RAJA AMPAT', 'MISOOL TIMUR', 'TOMOLOL', 'BUM DESA AT BEHEW TOMOLOL', 'BUMKam', 'Nama Terverifikasi'),
    (81, 'RAJA AMPAT', 'MISOOL TIMUR', 'USAHA JAYA', 'BUM DESA ATNE LEFO USAHA JAYA', 'BUMKam', 'Nama Terverifikasi'),
    (82, 'RAJA AMPAT', 'MISOOL TIMUR', 'LIMALAS TIMUR', 'BUM DESA JARANDI LIMALAS TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (83, 'RAJA AMPAT', 'MISOOL TIMUR', 'AUDAM', 'BUM DESA MAJU BERSAMA AUDAM', 'BUMKam', 'Nama Terverifikasi'),
    (84, 'RAJA AMPAT', 'MISOOL TIMUR', 'LIMALAS BARAT', 'BUM DESA AK KATAJUI LIMALAS BARAT', 'BUMKam', 'Nama Terverifikasi'),
    (85, 'RAJA AMPAT', 'WAIGEO BARAT', 'MUTUS', 'BUM DESA INGKONO DADI MUTUS', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (86, 'RAJA AMPAT', 'WAIGEO BARAT', 'BIANCI', 'BUM DESA BIANCI MBILIM BASEF BIANCI', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (87, 'RAJA AMPAT', 'WAIGEO BARAT', 'SALEO', 'BUM DESA WAYAG SALEO', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (88, 'RAJA AMPAT', 'WAIGEO BARAT', 'WAISILIP', 'BUM DESA BON MAMBRUK WAISILIP', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (89, 'RAJA AMPAT', 'TELUK MAYALIBIT', 'KALITOKO', 'BUM DESA SAMALIU KALITOKO', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (90, 'RAJA AMPAT', 'KOFIAU', 'DIBALAI', 'BUM DESA MIOS AIBU DIBALAI', 'BUMKam', 'Nama Terverifikasi'),
    (91, 'RAJA AMPAT', 'KOFIAU', 'TOLOBI', 'BUM DESA MAKMUR BERSAMA TOLOBI', 'BUMKam', 'Nama Terverifikasi'),
    (92, 'RAJA AMPAT', 'KOFIAU', 'DEER', 'BUM DESA WAMEI MAJU MANDIRI DEER', 'BUMKam', 'Nama Terverifikasi'),
    (93, 'RAJA AMPAT', 'KOFIAU', 'MIKIRAN', 'BUM DESA BONFAR MIKIRAN', 'BUMKam', 'Nama Terverifikasi'),
    (94, 'RAJA AMPAT', 'KOFIAU', 'AWAT', 'BUM DESA BOMBENANEM AWAT', 'BUMKam', 'Nama Terverifikasi'),
    (95, 'RAJA AMPAT', 'MEOS MANSAR', 'KAPISAWAR', 'BUM DESA SASWAR KAPISAWAR', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (96, 'RAJA AMPAT', 'MEOS MANSAR', 'SAWINGGRAI', 'BUM DESA KOMBRAN KAEM SAWINGGRAI', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (97, 'RAJA AMPAT', 'MEOS MANSAR', 'ARBOREK', 'BUM DESA ABU RAHMAN ARBOREK', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (98, 'RAJA AMPAT', 'MEOS MANSAR', 'KURKAPA', 'BUM DESA KOBE OSER KURKAPA', 'BUMKam', 'Nama Terverifikasi'),
    (99, 'RAJA AMPAT', 'MISOOL SELATAN', 'FAFANLAP', 'BUM DESA DAG LEFO FAFANLAP', 'BUMKam', 'Nama Terverifikasi'),
    (100, 'RAJA AMPAT', 'MISOOL SELATAN', 'YELLU', 'BUM DESA YELLU BERSAMA YELLU', 'BUMKam', 'Nama Terverifikasi'),
    (101, 'RAJA AMPAT', 'MISOOL SELATAN', 'HARAPAN JAYA', 'BUM DESA FI BESTO HARAPAN JAYA', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (102, 'RAJA AMPAT', 'MISOOL SELATAN', 'KAYEREPOP', 'BUM DESA ALBAROKAH KAYEREPOP', 'BUMKam', 'Nama Terverifikasi'),
    (103, 'RAJA AMPAT', 'MISOOL SELATAN', 'DABATAN', 'BUM DESA MAM SADI DABATAN', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (104, 'RAJA AMPAT', 'WAIGEO BARAT KEPULAUAN', 'PAM', 'BUM DESA AYA KADA PAM', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (105, 'RAJA AMPAT', 'WAIGEO BARAT KEPULAUAN', 'SAUKABU', 'BUM DESA LIBERTU SAUKABU', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (106, 'RAJA AMPAT', 'WAIGEO BARAT KEPULAUAN', 'GAG', 'BUM DESA YEF GAG', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (107, 'RAJA AMPAT', 'WAIGEO BARAT KEPULAUAN', 'SAUPAPIR', 'BUM DESA PAPIRDORET SAUPAPIR', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (108, 'RAJA AMPAT', 'MISOOL BARAT', 'LILINTA', 'BUM DESA FADAREL LILINTA', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (109, 'RAJA AMPAT', 'MISOOL BARAT', 'GAMTA', 'BUM DESA JIPAN GAMTA', 'BUMKam', 'Nama Terverifikasi'),
    (110, 'RAJA AMPAT', 'MISOOL BARAT', 'BIGA', 'BUM DESA KOFA BIGA', 'BUMKam', 'Nama Terverifikasi'),
    (111, 'RAJA AMPAT', 'TIPLOL MAYALIBIT', 'GO', 'BUM DESA GO GO', 'BUMKam', 'Nama Terverifikasi'),
    (112, 'RAJA AMPAT', 'TIPLOL MAYALIBIT', 'WAIFOI', 'BUM DESA BAMASU WAIFOI', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (113, 'RAJA AMPAT', 'TIPLOL MAYALIBIT', 'WARIMAK', 'BUM DESA BEKITEM WARIMAK', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (114, 'RAJA AMPAT', 'BATANTA UTARA', 'AREFI TIMUR', 'BUM DESA SAMPARIDEK AREFI TIMUR', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (115, 'RAJA AMPAT', 'SALAWATI TENGAH', 'WAIBU', 'BUM DESA WAIBU MEKAR TANI WAIBU', 'BUMKam', 'Nama Terverifikasi'),
    (116, 'RAJA AMPAT', 'SALAWATI TENGAH', 'WAILABU', 'BUM DESA MAJU JAYA WAILABU', 'BUMKam', 'Nama Terverifikasi'),
    (117, 'RAJA AMPAT', 'BATANTA SELATAN', 'YENANAS', 'BUM DESA ATLEFO YENANAS', 'BUMKam', 'Nama Terverifikasi'),
    (118, 'RAJA AMPAT', 'BATANTA SELATAN', 'AMDUI', 'BUM DESA KOBE OSER AMDUI', 'BUMKam', 'Nama Terverifikasi'),
    (119, 'RAJA AMPAT', 'BATANTA SELATAN', 'WAILEBET', 'BUM DESA AT CAMO WAILEBET', 'BUMKam', 'Nama Terverifikasi'),
    (120, 'RAJA AMPAT', 'BATANTA SELATAN', 'WAIMAN', 'BUM DESA NEWOLHSAI WAIMAN', 'BUMKam', 'Nama Terverifikasi'),
    (121, 'TAMBRAUW', 'YEMBUN', 'METNAYAM', 'BUM DESA YEMBUN BERSINAR METNAYAM', 'BUMKam', 'Nama Terverifikasi'),
    (122, 'TAMBRAUW', 'YEMBUN', 'SALEM', 'BUM DESA YEMBUN MAJU SALEM', 'BUMKam', 'Nama Terverifikasi'),
    (123, 'TAMBRAUW', 'KWOOR', 'ORWEN', 'BUM DESA CENDRAWASIH ORWEN', 'BUMKam', 'Nama Terverifikasi'),
    (124, 'TAMBRAUW', 'KWOOR', 'ESMAMBO', 'BUM DESA CINTA KASIH ESMAMBO', 'BUMKam', 'Nama Terverifikasi'),
    (125, 'TAMBRAUW', 'SAUSAPOR', 'UIGWEM', 'BUM DESA KAMPUNG UIGWEM UIGWEM', 'BUMKam', 'Perbaikan Nama'),
    (126, 'TAMBRAUW', 'BIKAR', 'WERUR', 'BUM DESA MANFADURU WERUR', 'BUMKam', 'Nama Terverifikasi'),
    (127, 'TAMBRAUW', 'BIKAR', 'WERWAF', 'BUM DESA MYOSSU WERWAF', 'BUMKam', 'Nama Terverifikasi'),
    (128, 'TAMBRAUW', 'BAMUSBAMA', 'WORMON', 'BUM DESA YEMBUN CAHAYA WORMON', 'BUMKam', 'Nama Terverifikasi'),
    (129, 'TAMBRAUW', 'ASES', 'SAFOTIEK', 'BUM DESA MAJU MANDIRI SAFOTIEK', 'BUMKam', 'Nama Terverifikasi'),
    (130, 'TAMBRAUW', 'ASES', 'FRASAYOAH', 'BUM DESA MAJU MANDIRI FRASAYOAH', 'BUMKam', 'Nama Terverifikasi'),
    (131, 'TAMBRAUW', 'MIYAH SELATAN', 'SAHAE', 'BUM DESA FRA WAMOH SAHAE', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (132, 'TAMBRAUW', 'TOBOUW', 'SUNGGAK', 'BUM DESA DONKE SUNGGAK', 'BUMKam', 'Nama Terverifikasi'),
    (133, 'TAMBRAUW', 'MAWABUAN', 'AFRAWI', 'BUM DESA IBORI AFRAWI', 'BUMKam', 'Nama Terverifikasi'),
    (134, 'TAMBRAUW', 'KEBAR TIMUR', 'UNTOREY', 'BUM DESA JAYA UNTOREY', 'BUMKam', 'Nama Terverifikasi'),
    (135, 'TAMBRAUW', 'KASI', 'MEIMORUFOF', 'BUM DESA AMIF JAYA BERSAMA MEIMORUFOF', 'BUMKam', 'Nama Terverifikasi'),
    (136, 'TAMBRAUW', 'KASI', 'KASI INDAH', 'BUM DESA NATASYA TUNAS KASI INDAH', 'BUMKam', 'Nama Terverifikasi'),
    (137, 'MAYBRAT', 'AIFAT', 'KUMURKEK', 'BUM DESA KUMBERS MART KUMURKEK', 'BUMKam', 'Nama Terverifikasi'),
    (138, 'MAYBRAT', 'AIFAT', 'SUSUMUK', 'BUM DESA KALI LIBUR SUSUMUK', 'BUMKam', 'Nama Terverifikasi'),
    (139, 'MAYBRAT', 'AIFAT', 'KOKAS', 'BUM DESA KOKAS SATU HATI KOKAS', 'BUMKam', 'Nama Terverifikasi'),
    (140, 'MAYBRAT', 'AIFAT', 'KOCUAS', 'BUM DESA ANEMANA LESTARI KOCUAS', 'BUMKam', 'Nama Terverifikasi'),
    (141, 'MAYBRAT', 'AIFAT', 'KOCUWER', 'BUM DESA MANDIRI KOCUWER', 'BUMKam', 'Nama Terverifikasi'),
    (142, 'MAYBRAT', 'AIFAT', 'BORI', 'BUM DESA WASE BORI MANDIRI BORI', 'BUMKam', 'Nama Terverifikasi'),
    (143, 'MAYBRAT', 'AIFAT', 'WERJAYA', 'BUM DESA MANDIRI WERJAYA', 'BUMKam', 'Nama Terverifikasi'),
    (144, 'MAYBRAT', 'AIFAT', 'TEHAHITE', 'BUM DESA KOMPISE TEHAHITE', 'BUMKam', 'Nama Terverifikasi'),
    (145, 'MAYBRAT', 'AIFAT', 'FAITMAYAF', 'BUM DESA ROFAS MART FAITMAYAF', 'BUMKam', 'Nama Terverifikasi'),
    (146, 'MAYBRAT', 'AIFAT', 'FUTON', 'BUM DESA FUTON FRSA FUTON', 'BUMKam', 'Nama Terverifikasi'),
    (147, 'MAYBRAT', 'AIFAT', 'SAMPIKA', 'BUM DESA FRAWEBO RANA SAMPIKA', 'BUMKam', 'Nama Terverifikasi'),
    (148, 'MAYBRAT', 'AIFAT', 'RIOF MASE*', 'BUM DESA MAMOS JAYA RIOF MASE*', 'BUMKam', 'Nama Terverifikasi'),
    (149, 'MAYBRAT', 'AIFAT', 'FAITSAWE', 'BUM DESA YEFUN FRA SEJAHTERA FAITSAWE', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (150, 'MAYBRAT', 'AIFAT', 'KOCUWER SELATAN', 'BUM DESA MANDIRI KOCUWER SELATAN', 'BUMKam', 'Nama Terverifikasi'),
    (151, 'MAYBRAT', 'AIFAT', 'FAITMAYAF BARAT', 'BUM DESA SAHBUR AYAMATO FAITMAYAF BARAT', 'BUMKam', 'Nama Terverifikasi'),
    (152, 'MAYBRAT', 'AIFAT', 'SIKOF', 'BUM DESA ATAVSUEN SIKOH SIKOF', 'BUMKam', 'Nama Terverifikasi'),
    (153, 'MAYBRAT', 'AIFAT', 'KUMURKEK BARAT', 'BUM DESA RAKAAM JAYA KUMURKEK BARAT', 'BUMKam', 'Nama Terverifikasi'),
    (154, 'MAYBRAT', 'AIFAT', 'AINOD', 'BUM DESA AINOD MART AINOD', 'BUMKam', 'Nama Terverifikasi'),
    (155, 'MAYBRAT', 'AIFAT', 'KOCUAS UTARA', 'BUM DESA ISWET RAMU KOCUAS UTARA', 'BUMKam', 'Nama Terverifikasi'),
    (156, 'MAYBRAT', 'AIFAT UTARA', 'AYAWASI', 'BUM DESA FRATEO AYAWASI', 'BUMKam', 'Nama Terverifikasi'),
    (157, 'MAYBRAT', 'AIFAT UTARA', 'AYAWASI SELATAN', 'BUM DESA UPAH AYAWASI SELATAN', 'BUMKam', 'Nama Terverifikasi'),
    (158, 'MAYBRAT', 'AIFAT UTARA', 'AYAWASI TIMUR', 'BUM DESA AYTIM JAYA AYAWASI TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (159, 'MAYBRAT', 'AIFAT UTARA', 'SUSAI', 'BUM DESA FUJIAMA SUSAI', 'BUMKam', 'Nama Terverifikasi'),
    (160, 'MAYBRAT', 'AIFAT UTARA', 'FONATU', 'BUM DESA AYAMATO FONATU', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (161, 'MAYBRAT', 'AIFAT UTARA', 'MOSUN', 'BUM DESA SRAHWATA MOSUN', 'BUMKam', 'Nama Terverifikasi'),
    (162, 'MAYBRAT', 'AIFAT UTARA', 'WAYANE', 'BUM DESA TABORITO WAYANE', 'BUMKam', 'Nama Terverifikasi'),
    (163, 'MAYBRAT', 'AIFAT UTARA', 'KONJA', 'BUM DESA FAIT SAVO KONJA', 'BUMKam', 'Nama Terverifikasi'),
    (164, 'MAYBRAT', 'AIFAT UTARA', 'YARAT', 'BUM DESA SRI FKAN YARAT', 'BUMKam', 'Nama Terverifikasi'),
    (165, 'MAYBRAT', 'AIFAT UTARA', 'MAN', 'BUM DESA SIEMBEWER MAN', 'BUMKam', 'Nama Terverifikasi'),
    (166, 'MAYBRAT', 'AIFAT UTARA', 'HOWAIT', 'BUM DESA FAITESIAR HOWAIT', 'BUMKam', 'Nama Terverifikasi'),
    (167, 'MAYBRAT', 'AIFAT UTARA', 'HAENKANES', 'BUM DESA ATAF SENAU GRUP HAENKANES', 'BUMKam', 'Nama Terverifikasi'),
    (168, 'MAYBRAT', 'AIFAT UTARA', 'KONJA BARAT', 'BUM DESA MANDIRI KONJA BARAT', 'BUMKam', 'Nama Terverifikasi'),
    (169, 'MAYBRAT', 'AIFAT UTARA', 'YARAT TIMUR', 'BUM DESA SEVAN YARAT TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (170, 'MAYBRAT', 'AIFAT UTARA', 'RAHA', 'BUM DESA ARAWERES JAYA RAHA', 'BUMKam', 'Nama Terverifikasi'),
    (171, 'MAYBRAT', 'AIFAT UTARA', 'MOWES', 'BUM DESA CHAMTOL MART MOWES', 'BUMKam', 'Nama Terverifikasi'),
    (172, 'MAYBRAT', 'AIFAT UTARA', 'IRATA', 'BUM DESA IRATA ARAKATIAR IRATA', 'BUMKam', 'Nama Terverifikasi'),
    (173, 'MAYBRAT', 'AIFAT UTARA', 'NESET', 'BUM DESA MANDIRI NESET', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (174, 'MAYBRAT', 'AIFAT UTARA', 'MOSUN TIMUR', 'BUM DESA RASER MOSUN TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (175, 'MAYBRAT', 'AIFAT UTARA', 'MOSUN UTARA', 'BUM DESA AYAMATO MOSUN UTARA', 'BUMKam', 'Nama Terverifikasi'),
    (176, 'MAYBRAT', 'AIFAT TIMUR', 'AISA', 'BUM DESA SARBUKUN AISA', 'BUMKam', 'Nama Terverifikasi'),
    (177, 'MAYBRAT', 'AIFAT TIMUR', 'AIKRER', 'BUM DESA ATAF MUO AIKRER', 'BUMKam', 'Nama Terverifikasi'),
    (178, 'MAYBRAT', 'AIFAT TIMUR', 'AITREM', 'BUM DESA POMBAIR AITREM', 'BUMKam', 'Nama Terverifikasi'),
    (179, 'MAYBRAT', 'AIFAT TIMUR', 'SAWIN', 'BUM DESA MUBERS MANDIRI SAWIN', 'BUMKam', 'Nama Terverifikasi'),
    (180, 'MAYBRAT', 'AIFAT TIMUR', 'SAHBUKU', 'BUM DESA TAFUSUT SRENEN MANDIRI SAHBUKU', 'BUMKam', 'Perbaikan Nama'),
    (181, 'MAYBRAT', 'AIFAT TIMUR', 'SASIOR FRABUKU', 'BUM DESA KUSUD MANDIRI SASIOR FRABUKU', 'BUMKam', 'Nama Terverifikasi'),
    (182, 'MAYBRAT', 'AIFAT TIMUR', 'WAKOM', 'BUM DESA WAKOM BERSAUDARA WAKOM', 'BUMKam', 'Nama Terverifikasi'),
    (183, 'MAYBRAT', 'AIFAT TIMUR', 'SANEM', 'BUM DESA HAITAU SANEM', 'BUMKam', 'Nama Terverifikasi'),
    (184, 'MAYBRAT', 'AIFAT TIMUR', 'BUOH SA', 'BUM DESA BUOHSA MANDIRI BUOH SA', 'BUMKam', 'Nama Terverifikasi'),
    (185, 'MAYBRAT', 'AIFAT SELATAN', 'KISOR', 'BUM DESA IMAYOH KISOR', 'BUMKam', 'Nama Terverifikasi'),
    (186, 'MAYBRAT', 'AIFAT SELATAN', 'SORRY', 'BUM DESA SORRY MANDIRI SORRY', 'BUMKam', 'Nama Terverifikasi'),
    (187, 'MAYBRAT', 'AIFAT SELATAN', 'IMSUN', 'BUM DESA KAREF MANJA IMSUN', 'BUMKam', 'Nama Terverifikasi'),
    (188, 'MAYBRAT', 'AIFAT SELATAN', 'SABAH', 'BUM DESA FATEM SABAH', 'BUMKam', 'Nama Terverifikasi'),
    (189, 'MAYBRAT', 'AIFAT SELATAN', 'TAHSIMARA', 'BUM DESA MOTOM MANDIRI SEJAHTERA TAHSIMARA', 'BUMKam', 'Nama Terverifikasi'),
    (190, 'MAYBRAT', 'AIFAT SELATAN', 'FUOG', 'BUM DESA KAIWA FUOG', 'BUMKam', 'Nama Terverifikasi'),
    (191, 'MAYBRAT', 'AIFAT SELATAN', 'ASIAF SAMAN', 'BUM DESA ASIAFSAMAN SEJAHTERA ASIAF SAMAN', 'BUMKam', 'Nama Terverifikasi'),
    (192, 'MAYBRAT', 'AIFAT SELATAN', 'HORA IEK', 'BUM DESA LEKHOR MANDIRI HORA IEK', 'BUMKam', 'Nama Terverifikasi'),
    (193, 'MAYBRAT', 'AIFAT SELATAN', 'FUOG SELATAN', 'BUM DESA GINAMU FUOG SELATAN', 'BUMKam', 'Nama Terverifikasi'),
    (194, 'MAYBRAT', 'AIFAT SELATAN', 'SAME RAKATOR', 'BUM DESA YHOTIAM SAME RAKATOR', 'BUMKam', 'Nama Terverifikasi'),
    (195, 'MAYBRAT', 'AIFAT SELATAN', 'ROMA', 'BUM DESA ROMA SEJAHTERA ROMA', 'BUMKam', 'Nama Terverifikasi'),
    (196, 'MAYBRAT', 'AIFAT SELATAN', 'KRUS', 'BUM DESA SFOHE SEJAHTERA KRUS', 'BUMKam', 'Nama Terverifikasi'),
    (197, 'MAYBRAT', 'AIFAT SELATAN', 'AWET MAIN', 'BUM DESA FAITSISIYET AWET MAIN', 'BUMKam', 'Nama Terverifikasi'),
    (198, 'MAYBRAT', 'AIFAT SELATAN', 'YEEK', 'BUM DESA YEEK MANDIRI YEEK', 'BUMKam', 'Nama Terverifikasi'),
    (199, 'MAYBRAT', 'AIFAT SELATAN', 'EDEN*', 'BUM DESA FRAMBAT JAYA EDEN*', 'BUMKam', 'Nama Terverifikasi'),
    (200, 'MAYBRAT', 'AIFAT SELATAN', 'TOLAK', 'BUM DESA ABESO TOLAK', 'BUMKam', 'Nama Terverifikasi'),
    (201, 'MAYBRAT', 'AITINYO BARAT', 'KAMBUFATEM', 'BUM DESA KOTENG KAMBUFATEM', 'BUMKam', 'Nama Terverifikasi'),
    (202, 'MAYBRAT', 'AITINYO BARAT', 'KAMBUFATEM UTARA', 'BUM DESA SUBRU KAMBUFATEM UTARA', 'BUMKam', 'Nama Terverifikasi'),
    (203, 'MAYBRAT', 'AITINYO BARAT', 'HOSYO ATA', 'BUM DESA FETMARUS HOSYO ATA', 'BUMKam', 'Nama Terverifikasi'),
    (204, 'MAYBRAT', 'AITINYO BARAT', 'WAYBOMATAH', 'BUM DESA FRAKOMI WAYBOMATAH', 'BUMKam', 'Nama Terverifikasi'),
    (205, 'MAYBRAT', 'AITINYO BARAT', 'SIYO', 'BUM DESA KAKTEN SIYO', 'BUMKam', 'Nama Terverifikasi'),
    (206, 'MAYBRAT', 'AITINYO BARAT', 'HASWEH', 'BUM DESA RIWYAS HASWEH', 'BUMKam', 'Nama Terverifikasi'),
    (207, 'MAYBRAT', 'AITINYO BARAT', 'HOSYO BANAH', 'BUM DESA KOKER HOSYO BANAH', 'BUMKam', 'Nama Terverifikasi'),
    (208, 'MAYBRAT', 'AITINYO', 'AITINYO', 'BUM DESA MAKBEN AITINYO AITINYO', 'BUMKam', 'Nama Terverifikasi'),
    (209, 'MAYBRAT', 'AITINYO', 'IROHE', 'BUM DESA IROHE SEJAHTERA IROHE', 'BUMKam', 'Nama Terverifikasi'),
    (210, 'MAYBRAT', 'AITINYO', 'SRIS', 'BUM DESA PAPUA SRIS', 'BUMKam', 'Nama Terverifikasi'),
    (211, 'MAYBRAT', 'AITINYO', 'KAMRO', 'BUM DESA SYA MBE NAIT KAMRO', 'BUMKam', 'Nama Terverifikasi'),
    (212, 'MAYBRAT', 'AITINYO', 'KARSU', 'BUM DESA KARSU JAYA KARSU', 'BUMKam', 'Nama Terverifikasi'),
    (213, 'MAYBRAT', 'AITINYO', 'TEHAK KECIL', 'BUM DESA TEHAK KECIL TEHAK KECIL', 'BUMKam', 'Perbaikan Nama'),
    (214, 'MAYBRAT', 'AITINYO', 'SIRA AYA', 'BUM DESA SIRAAYA MANDIRI SIRA AYA', 'BUMKam', 'Nama Terverifikasi'),
    (215, 'MAYBRAT', 'AITINYO', 'KOROM', 'BUM DESA MARKOM JAYA KOROM', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (216, 'MAYBRAT', 'AITINYO', 'SUMANIS', 'BUM DESA MONSRUH SUMANIS', 'BUMKam', 'Nama Terverifikasi'),
    (217, 'MAYBRAT', 'AITINYO', 'IBASUF', 'BUM DESA IBASUF MANDIRI JAYA IBASUF', 'BUMKam', 'Nama Terverifikasi'),
    (218, 'MAYBRAT', 'AITINYO', 'SUBIN', 'BUM DESA SUBIN MADIRI SUBIN', 'BUMKam', 'Nama Terverifikasi'),
    (219, 'MAYBRAT', 'AITINYO', 'IROHMRAR', 'BUM DESA UTBIR MANDIRI IROHMRAR', 'BUMKam', 'Nama Terverifikasi'),
    (220, 'MAYBRAT', 'AITINYO', 'TEHAK BARAT*', 'BUM DESA BUM DESA TEHAK BARAT*', 'BUMKam', 'Nama Terverifikasi'),
    (221, 'MAYBRAT', 'AITINYO', 'WIHO', 'BUM DESA IKROR WIHO', 'BUMKam', 'Nama Terverifikasi'),
    (222, 'MAYBRAT', 'AITINYO', 'KAMRO SELATAN', 'BUM DESA ANU BETA SIRET KAMRO SELATAN', 'BUMKam', 'Nama Terverifikasi'),
    (223, 'MAYBRAT', 'AITINYO UTARA', 'FAN', 'BUM DESA ISYAR FAN', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (224, 'MAYBRAT', 'AITINYO UTARA', 'ASMURUF U', 'BUM DESA HAES BERSAMA ASMURUF U', 'BUMKam', 'Nama Terverifikasi'),
    (225, 'MAYBRAT', 'AITINYO UTARA', 'MIRAFAAN', 'BUM DESA MAKMUR MIRAFAAN', 'BUMKam', 'Nama Terverifikasi'),
    (226, 'MAYBRAT', 'AITINYO UTARA', 'ASMURUF TEE', 'BUM DESA FASUM ASMURUF TEE', 'BUMKam', 'Nama Terverifikasi'),
    (227, 'MAYBRAT', 'AITINYO UTARA', 'TEHAK TEE', 'BUM DESA ANFAT JAYA TEHAK TEE', 'BUMKam', 'Nama Terverifikasi'),
    (228, 'MAYBRAT', 'AITINYO UTARA', 'FRAMAFIR', 'BUM DESA AIT SYAIR FRAMAFIR', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (229, 'MAYBRAT', 'AITINYO UTARA', 'SUBRIT', 'BUM DESA UMDESS INDAH SUBRIT', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (230, 'MAYBRAT', 'AITINYO UTARA', 'INTA', 'BUM DESA AIS MANDIRI INTA', 'BUMKam', 'Nama Terverifikasi'),
    (231, 'MAYBRAT', 'AYAMARU', 'FRAMU', 'BUM DESA MOS FRAMU JAYA FRAMU', 'BUMKam', 'Nama Terverifikasi'),
    (232, 'MAYBRAT', 'AYAMARU', 'MEFKAJIM II', 'BUM DESA ROH MBY MEFKAJIM II', 'BUMKam', 'Nama Terverifikasi'),
    (233, 'MAYBRAT', 'AYAMARU', 'FRAHARO', 'BUM DESA SIKO WEFO FRAHARO', 'BUMKam', 'Nama Terverifikasi'),
    (234, 'MAYBRAT', 'AYAMARU', 'SMUSSWIOH', 'BUM DESA FOMBAT SMUSSWIOH', 'BUMKam', 'Nama Terverifikasi'),
    (235, 'MAYBRAT', 'AYAMARU', 'TWER', 'BUM DESA SRISA TWER', 'BUMKam', 'Nama Terverifikasi'),
    (236, 'MAYBRAT', 'AYAMARU', 'AFES', 'BUM DESA AFES JAYA AFES', 'BUMKam', 'Nama Terverifikasi'),
    (237, 'MAYBRAT', 'AYAMARU', 'TUSO', 'BUM DESA ATTA SEJAHTERA TUSO', 'BUMKam', 'Nama Terverifikasi'),
    (238, 'MAYBRAT', 'AYAMARU UTARA', 'YUBIAH', 'BUM DESA FAUD YUBIAH', 'BUMKam', 'Nama Terverifikasi'),
    (239, 'MAYBRAT', 'AYAMARU UTARA', 'KARETUBUN', 'BUM DESA SEJAHTERA KARETUBUN', 'BUMKam', 'Nama Terverifikasi'),
    (240, 'MAYBRAT', 'AYAMARU UTARA', 'SETTA', 'BUM DESA SEJAHTERA SETTA', 'BUMKam', 'Nama Terverifikasi'),
    (241, 'MAYBRAT', 'AYAMARU UTARA', 'HOHOYOR', 'BUM DESA WATIR JAYA HOHOYOR', 'BUMKam', 'Dokumen Badan Hukum Terverifikasi'),
    (242, 'MAYBRAT', 'AYAMARU UTARA', 'ARNE', 'BUM DESA TUMARU ARNE', 'BUMKam', 'Nama Terverifikasi'),
    (243, 'MAYBRAT', 'AYAMARU UTARA', 'AUS TIWIT', 'BUM DESA MAKMUR AUS TIWIT', 'BUMKam', 'Nama Terverifikasi'),
    (244, 'MAYBRAT', 'AYAMARU UTARA', 'JOHAFAH', 'BUM DESA WARJO PERMAI JOHAFAH', 'BUMKam', 'Nama Terverifikasi'),
    (245, 'MAYBRAT', 'AYAMARU UTARA', 'YUKASE', 'BUM DESA AYUT PERMATA YUKASE', 'BUMKam', 'Nama Terverifikasi'),
    (246, 'MAYBRAT', 'AYAMARU UTARA', 'SERMA', 'BUM DESA SERMA MANDIRI SERMA', 'BUMKam', 'Nama Terverifikasi'),
    (247, 'MAYBRAT', 'AYAMARU UTARA', 'KFAA', 'BUM DESA SEJAHTERA KFAA', 'BUMKam', 'Nama Terverifikasi'),
    (248, 'MAYBRAT', 'AYAMARU UTARA', 'ARNE TIMUR', 'BUM DESA FEJANA ARNE TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (249, 'MAYBRAT', 'AYAMARU UTARA', 'NAUWITA', 'BUM DESA ARMEYU NAUWITA', 'BUMKam', 'Nama Terverifikasi'),
    (250, 'MAYBRAT', 'AYAMARU TIMUR', 'KAMBUAYA', 'BUM DESA SAKOFTIS KAMBUAYA', 'BUMKam', 'Nama Terverifikasi'),
    (251, 'MAYBRAT', 'AYAMARU TIMUR', 'FAITMAJIN', 'BUM DESA RANU SAU FAITMAJIN', 'BUMKam', 'Nama Terverifikasi'),
    (252, 'MAYBRAT', 'AYAMARU TIMUR', 'SEFAYIT', 'BUM DESA ANU BETA TUBAT SEFAYIT', 'BUMKam', 'Nama Terverifikasi'),
    (253, 'MAYBRAT', 'AYAMARU TIMUR', 'INSAS', 'BUM DESA YOHAI GROUP INSAS', 'BUMKam', 'Nama Terverifikasi'),
    (254, 'MAYBRAT', 'MARE', 'SUSWA', 'BUM DESA KUMBER SUSWA', 'BUMKam', 'Nama Terverifikasi'),
    (255, 'MAYBRAT', 'MARE', 'SEYA', 'BUM DESA KOKFERE SEYO SEYA', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (256, 'MAYBRAT', 'MARE', 'WABAN', 'BUM DESA BEBAM WABAN', 'BUMKam', 'Nama Terverifikasi'),
    (257, 'MAYBRAT', 'MARE', 'KOMBIF', 'BUM DESA MATOWAYA KOMBIF', 'BUMKam', 'Nama Terverifikasi'),
    (258, 'MAYBRAT', 'MARE', 'RUFASES', 'BUM DESA WEKU RUFASES', 'BUMKam', 'Nama Terverifikasi'),
    (259, 'MAYBRAT', 'MARE', 'BAKRABI', 'BUM DESA FAYENU BAKRABI', 'BUMKam', 'Nama Terverifikasi'),
    (260, 'MAYBRAT', 'MARE', 'NAFASI', 'BUM DESA CIVAS NAFASI', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (261, 'MAYBRAT', 'MARE', 'MAHOS', 'BUM DESA SUSA MAHOS', 'BUMKam', 'Nama Terverifikasi'),
    (262, 'MAYBRAT', 'MARE', 'SAWO', 'BUM DESA WORO SAWO', 'BUMKam', 'Nama Terverifikasi'),
    (263, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'MUPAS', 'BUM DESA MUPAS BERSAUDARA MUPAS', 'BUMKam', 'Nama Terverifikasi'),
    (264, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'KAMAT', 'BUM DESA MOSACO KAMAT', 'BUMKam', 'Nama Terverifikasi'),
    (265, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'FRAMBU', 'BUM DESA FRAMBU MANDIRI FRAMBU', 'BUMKam', 'Nama Terverifikasi'),
    (266, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'AYATA', 'BUM DESA YAMAS AYATA', 'BUMKam', 'Nama Terverifikasi'),
    (267, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'AIKUS', 'BUM DESA SEMWAR MANDIRI AIKUS', 'BUMKam', 'Nama Terverifikasi'),
    (268, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'AIWESA', 'BUM DESA FAUMIR AIWESA', 'BUMKam', 'Nama Terverifikasi'),
    (269, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'PITOR', 'BUM DESA PITOR MANDIRI PITOR', 'BUMKam', 'Nama Terverifikasi'),
    (270, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'AIFAM', 'BUM DESA AYAMUO JAYA AIFAM', 'BUMKam', 'Nama Terverifikasi'),
    (271, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'SAUD', 'BUM DESA ANE SAUD', 'BUMKam', 'Nama Terverifikasi'),
    (272, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'TIAM', 'BUM DESA ANEMAFOS TIAM', 'BUMKam', 'Nama Terverifikasi'),
    (273, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'FAAN KAHRIO', 'BUM DESA FAAN KAHRIO MANDIRI FAAN KAHRIO', 'BUMKam', 'Nama Terverifikasi'),
    (274, 'MAYBRAT', 'AIFAT TIMUR TENGAH', 'ASSEM', 'BUM DESA SOSMERE JAYA ASSEM', 'BUMKam', 'Nama Terverifikasi'),
    (275, 'MAYBRAT', 'AIFAT TIMUR JAUH', 'AINESRA', 'BUM DESA AINESRA JAYA AINESRA', 'BUMKam', 'Nama Terverifikasi'),
    (276, 'MAYBRAT', 'AIFAT TIMUR JAUH', 'AIMAU', 'BUM DESA EHIS JAYA AIMAU', 'BUMKam', 'Nama Terverifikasi'),
    (277, 'MAYBRAT', 'AIFAT TIMUR JAUH', 'MESYAM', 'BUM DESA BUSYAM UKNASEN START MESYAM', 'BUMKam', 'Nama Terverifikasi'),
    (278, 'MAYBRAT', 'AIFAT TIMUR JAUH', 'AISASIOR', 'BUM DESA KOPERMAS KALI BIRU SEJAHTERA AISASIOR', 'BUMKam', 'Nama Terverifikasi'),
    (279, 'MAYBRAT', 'AIFAT TIMUR JAUH', 'FRANEWAY', 'BUM DESA AIMAKOT MINING FRANEWAY', 'BUMKam', 'Nama Terverifikasi'),
    (280, 'MAYBRAT', 'AIFAT TIMUR JAUH', 'AIKINGGING', 'BUM DESA PEMUDA WAYMESAN  JAYA AIKINGGING', 'BUMKam', 'Nama Terverifikasi'),
    (281, 'MAYBRAT', 'AIFAT TIMUR JAUH', 'TIEFROMEN', 'BUM DESA UKOZGUG JAYA TIEFROMEN', 'BUMKam', 'Nama Terverifikasi'),
    (282, 'MAYBRAT', 'AIFAT TIMUR SELATAN', 'WORMU', 'BUM DESA MOSFUOM JAYA WORMU', 'BUMKam', 'Perbaikan Nama'),
    (283, 'MAYBRAT', 'AIFAT TIMUR SELATAN', 'MAKIRI', 'BUM DESA WAREMBA PERMAI MAKIRI', 'BUMKam', 'Nama Terverifikasi'),
    (284, 'MAYBRAT', 'AIFAT TIMUR SELATAN', 'WARBA', 'BUM DESA MARSI SUKSES WARBA', 'BUMKam', 'Perbaikan Nama'),
    (285, 'MAYBRAT', 'AIFAT TIMUR SELATAN', 'WINUNI', 'BUM DESA AIKEK MANDIRI WINUNI', 'BUMKam', 'Nama Terverifikasi'),
    (286, 'MAYBRAT', 'AIFAT TIMUR SELATAN', 'SRUMATE', 'BUM DESA SOFSEHAIN MANDIRI SRUMATE', 'BUMKam', 'Nama Terverifikasi'),
    (287, 'MAYBRAT', 'AIFAT TIMUR SELATAN', 'WOMBA', 'BUM DESA SOHROON PERMAI WOMBA', 'BUMKam', 'Nama Terverifikasi'),
    (288, 'MAYBRAT', 'AYAMARU SELATAN', 'SAUF', 'BUM DESA TEMU KARYA SAUF', 'BUMKam', 'Nama Terverifikasi'),
    (289, 'MAYBRAT', 'AYAMARU SELATAN', 'SEMBARO', 'BUM DESA HAVSEN MANDIRI SEMBARO', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (290, 'MAYBRAT', 'AYAMARU SELATAN', 'KOMA KOMA', 'BUM DESA BOHARAR JAYA KOMA KOMA', 'BUMKam', 'Nama Terverifikasi'),
    (291, 'MAYBRAT', 'AYAMARU SELATAN', 'KANISABAR', 'BUM DESA KANISABAR MANDIRI KANISABAR', 'BUMKam', 'Nama Terverifikasi'),
    (292, 'MAYBRAT', 'AYAMARU SELATAN', 'SFARARE', 'BUM DESA SERAFA MANDIRI SFARARE', 'BUMKam', 'Nama Terverifikasi'),
    (293, 'MAYBRAT', 'AYAMARU SELATAN', 'SANEH', 'BUM DESA ORMAN MANDIRI SANEH', 'BUMKam', 'Nama Terverifikasi'),
    (294, 'MAYBRAT', 'AYAMARU SELATAN', 'LEMAUK KLIT', 'BUM DESA FAJAR SRAHEN LEMAUK KLIT', 'BUMKam', 'Nama Terverifikasi'),
    (295, 'MAYBRAT', 'AYAMARU SELATAN', 'HAWIOH', 'BUM DESA HACOM JAYA HAWIOH', 'BUMKam', 'Nama Terverifikasi'),
    (296, 'MAYBRAT', 'AYAMARU SELATAN', 'SIMIYAH', 'BUM DESA SEDELET SEJAHTERA SIMIYAH', 'BUMKam', 'Nama Terverifikasi'),
    (297, 'MAYBRAT', 'AYAMARU SELATAN', 'SAGRIM', 'BUM DESA BUWIA JAYA SAGRIM', 'BUMKam', 'Nama Terverifikasi'),
    (298, 'MAYBRAT', 'AYAMARU JAYA', 'ADOH', 'BUM DESA FAYOH BARAT ADOH', 'BUMKam', 'Nama Terverifikasi'),
    (299, 'MAYBRAT', 'AYAMARU JAYA', 'TEMEL', 'BUM DESA MANDIRI TEMEL', 'BUMKam', 'Nama Terverifikasi'),
    (300, 'MAYBRAT', 'AYAMARU JAYA', 'SOSIAN', 'BUM DESA MANDIRI SOSIAN', 'BUMKam', 'Nama Terverifikasi'),
    (301, 'MAYBRAT', 'AYAMARU JAYA', 'SEGIOR', 'BUM DESA BOLSEMAR SEGIOR', 'BUMKam', 'Nama Terverifikasi'),
    (302, 'MAYBRAT', 'AYAMARU JAYA', 'ORAIN', 'BUM DESA AMAR ORAIN', 'BUMKam', 'Nama Terverifikasi'),
    (303, 'MAYBRAT', 'AYAMARU JAYA', 'RAWAS', 'BUM DESA HASNAR JAYA RAWAS', 'BUMKam', 'Nama Terverifikasi'),
    (304, 'MAYBRAT', 'AYAMARU JAYA', 'ORSU', 'BUM DESA MRAR ORSU ITRAH ORSU', 'BUMKam', 'Nama Terverifikasi'),
    (305, 'MAYBRAT', 'AYAMARU JAYA', 'SOAN', 'BUM DESA MANDIRI SOAN', 'BUMKam', 'Nama Terverifikasi'),
    (306, 'MAYBRAT', 'AYAMARU JAYA', 'WARBO', 'BUM DESA WARCIT WARBO', 'BUMKam', 'Nama Terverifikasi'),
    (307, 'MAYBRAT', 'AYAMARU JAYA', 'WOMAN', 'BUM DESA MAKMUR WOMAN', 'BUMKam', 'Nama Terverifikasi'),
    (308, 'MAYBRAT', 'AYAMARU SELATAN JAYA', 'FAITSIMAR', 'BUM DESA FAITSIMAR MANDIRI FAITSIMAR', 'BUMKam', 'Nama Terverifikasi'),
    (309, 'MAYBRAT', 'AYAMARU SELATAN JAYA', 'KOFAIT', 'BUM DESA FAITMABE MANDIRI KOFAIT', 'BUMKam', 'Nama Terverifikasi'),
    (310, 'MAYBRAT', 'AYAMARU TIMUR SELATAN', 'KAMBUSKATO', 'BUM DESA MAYOR KAMBU KAMBUSKATO', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (311, 'MAYBRAT', 'AYAMARU TIMUR SELATAN', 'KAMBUSKATO UTARA', 'BUM DESA WORMAF JAYA KAMBUSKATO UTARA', 'BUMKam', 'Nama Terverifikasi'),
    (312, 'MAYBRAT', 'AYAMARU TIMUR SELATAN', 'KAMBUIFA', 'BUM DESA IFAKAMBU KAMBUIFA', 'BUMKam', 'Nama Terverifikasi'),
    (313, 'MAYBRAT', 'AYAMARU TIMUR SELATAN', 'ISUSU', 'BUM DESA KANA ISUSU', 'BUMKam', 'Nama Terverifikasi'),
    (314, 'MAYBRAT', 'AYAMARU TIMUR SELATAN', 'MANO', 'BUM DESA RANU SAU MANO', 'BUMKam', 'Nama Terverifikasi'),
    (315, 'MAYBRAT', 'AYAMARU TIMUR SELATAN', 'SIPAT', 'BUM DESA SUMBAIR MANDIRI SIPAT', 'BUMKam', 'Nama Terverifikasi'),
    (316, 'MAYBRAT', 'AYAMARU TIMUR SELATAN', 'FAITWOSUR/ANGKASA PURA', 'BUM DESA FORMA FAITWOSUR/ANGKASA PURA', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (317, 'MAYBRAT', 'AYAMARU UTARA TIMUR', 'MAPURA', 'BUM DESA SIJIK MANDIRI MAPURA', 'BUMKam', 'Nama Terverifikasi'),
    (318, 'MAYBRAT', 'AYAMARU UTARA TIMUR', 'SUWIAM', 'BUM DESA SUFAN SUWIAM', 'BUMKam', 'Nama Terverifikasi'),
    (319, 'MAYBRAT', 'AYAMARU UTARA TIMUR', 'TOMASE', 'BUM DESA SIO TOMASE', 'BUMKam', 'Nama Terverifikasi'),
    (320, 'MAYBRAT', 'AYAMARU UTARA TIMUR', 'FRABO', 'BUM DESA FRABOH MANDIRI FRABO', 'BUMKam', 'Nama Terverifikasi'),
    (321, 'MAYBRAT', 'AYAMARU UTARA TIMUR', 'KARFA', 'BUM DESA FAJAR KARFA', 'BUMKam', 'Nama Terverifikasi'),
    (322, 'MAYBRAT', 'AYAMARU UTARA TIMUR', 'KONA', 'BUM DESA FRA MANA TUV KONA', 'BUMKam', 'Nama Terverifikasi'),
    (323, 'MAYBRAT', 'AYAMARU UTARA TIMUR', 'KOSAH', 'BUM DESA SAMAR KOSAH', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (324, 'MAYBRAT', 'AYAMARU TENGAH', 'KARTAPURA', 'BUM DESA KARTAPURA MANDIRI KARTAPURA', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (325, 'MAYBRAT', 'AYAMARU TENGAH', 'MEN', 'BUM DESA MEN MANDIRI MEN', 'BUMKam', 'Nama Terverifikasi'),
    (326, 'MAYBRAT', 'AYAMARU TENGAH', 'FAITCROAN*', 'BUM DESA KAMESTUT  SEJAHTERA FAITCROAN*', 'BUMKam', 'Perbaikan Dokumen Badan Hukum'),
    (327, 'MAYBRAT', 'AYAMARU TENGAH', 'ISME', 'BUM DESA KALBIR MANDIRI ISME', 'BUMKam', 'Nama Terverifikasi'),
    (328, 'MAYBRAT', 'AYAMARU TENGAH', 'RINDU', 'BUM DESA RINDU MANDIRI JAYA RINDU', 'BUMKam', 'Nama Terverifikasi'),
    (329, 'MAYBRAT', 'AYAMARU TENGAH', 'TUT', 'BUM DESA TUT MANDIRI TUT', 'BUMKam', 'Nama Terverifikasi'),
    (330, 'MAYBRAT', 'AYAMARU TENGAH', 'YOHWER', 'BUM DESA YOHWER BINTANG TIMUR YOHWER', 'BUMKam', 'Nama Terverifikasi'),
    (331, 'MAYBRAT', 'AYAMARU TENGAH', 'HUFIOH', 'BUM DESA HUFIOH MANDIRI HUFIOH', 'BUMKam', 'Nama Terverifikasi'),
    (332, 'MAYBRAT', 'AYAMARU TENGAH', 'WEVO*', 'BUM DESA WEVO MANDIRI WEVO*', 'BUMKam', 'Nama Terverifikasi'),
    (333, 'MAYBRAT', 'AYAMARU BARAT', 'SOROAN', 'BUM DESA WENSY PERMAI SOROAN', 'BUMKam', 'Nama Terverifikasi'),
    (334, 'MAYBRAT', 'AYAMARU BARAT', 'FANSE', 'BUM DESA CITRA PERMAI FANSE', 'BUMKam', 'Nama Terverifikasi'),
    (335, 'MAYBRAT', 'AYAMARU BARAT', 'CHALIAT', 'BUM DESA ABLET PERMAI CHALIAT', 'BUMKam', 'Nama Terverifikasi'),
    (336, 'MAYBRAT', 'AYAMARU BARAT', 'SFACKO', 'BUM DESA FEITMARU SFACKO', 'BUMKam', 'Nama Terverifikasi'),
    (337, 'MAYBRAT', 'AYAMARU BARAT', 'SEHU', 'BUM DESA SITMIA SEHU', 'BUMKam', 'Nama Terverifikasi'),
    (338, 'MAYBRAT', 'AYAMARU BARAT', 'TBO', 'BUM DESA SEWAYON JAYA TBO', 'BUMKam', 'Nama Terverifikasi'),
    (339, 'MAYBRAT', 'AYAMARU BARAT', 'SIEN', 'BUM DESA WADIL PERMAI SIEN', 'BUMKam', 'Nama Terverifikasi'),
    (340, 'MAYBRAT', 'AYAMARU BARAT', 'SFARAKA', 'BUM DESA BARMAK SFARAKA', 'BUMKam', 'Nama Terverifikasi'),
    (341, 'MAYBRAT', 'AITINYO TENGAH', 'EROKWERO', 'BUM DESA IFABO EROKWERO', 'BUMKam', 'Nama Terverifikasi'),
    (342, 'MAYBRAT', 'AITINYO TENGAH', 'SABUN', 'BUM DESA ARAMITIS SABUN SABUN', 'BUMKam', 'Nama Terverifikasi'),
    (343, 'MAYBRAT', 'AITINYO TENGAH', 'SIRA TEE', 'BUM DESA SIRA TEE JAYA SIRA TEE', 'BUMKam', 'Nama Terverifikasi'),
    (344, 'MAYBRAT', 'AITINYO TENGAH', 'WAY ''U''', 'BUM DESA HARU IMANE WAY ''U''', 'BUMKam', 'Nama Terverifikasi'),
    (345, 'MAYBRAT', 'AITINYO TENGAH', 'IROH SOHSER', 'BUM DESA SOHSER BLESING IROH SOHSER', 'BUMKam', 'Nama Terverifikasi'),
    (346, 'MAYBRAT', 'AITINYO TENGAH', 'FRAMBOH', 'BUM DESA PUTRA FRAMBOH FRAMBOH', 'BUMKam', 'Nama Terverifikasi'),
    (347, 'MAYBRAT', 'AITINYO TENGAH', 'KASAR*', 'BUM DESA SINAREH  LESTARI KASAR*', 'BUMKam', 'Nama Terverifikasi'),
    (348, 'MAYBRAT', 'AITINYO RAYA', 'JITMAU', 'BUM DESA ITAS JITMAU', 'BUMKam', 'Nama Terverifikasi'),
    (349, 'MAYBRAT', 'AITINYO RAYA', 'IKUF', 'BUM DESA FORSA IKUF', 'BUMKam', 'Nama Terverifikasi'),
    (350, 'MAYBRAT', 'AITINYO RAYA', 'ISIR', 'BUM DESA FOSKAYA ISIR', 'BUMKam', 'Nama Terverifikasi'),
    (351, 'MAYBRAT', 'AITINYO RAYA', 'JITMAU TIMUR', 'BUM DESA HUYA BERSATU JITMAU TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (352, 'MAYBRAT', 'AITINYO RAYA', 'IKUF UTARA', 'BUM DESA IMSU IKUF UTARA', 'BUMKam', 'Nama Terverifikasi'),
    (353, 'MAYBRAT', 'AITINYO RAYA', 'SARIMO', 'BUM DESA TOBAF SARIMO', 'BUMKam', 'Nama Terverifikasi'),
    (354, 'MAYBRAT', 'AITINYO RAYA', 'KAMBUSABO', 'BUM DESA TOTOR KAMBUSABO', 'BUMKam', 'Nama Terverifikasi'),
    (355, 'MAYBRAT', 'AITINYO RAYA', 'SRIRTABAM', 'BUM DESA FRATUTU SRIRTABAM', 'BUMKam', 'Nama Terverifikasi'),
    (356, 'MAYBRAT', 'AITINYO RAYA', 'IWAJIT*', 'BUM DESA FAAKRUF FAITHOWES IWAJIT*', 'BUMKam', 'Nama Terverifikasi'),
    (357, 'MAYBRAT', 'AITINYO RAYA', 'YUMAME', 'BUM DESA WAKISA YUMAME', 'BUMKam', 'Nama Terverifikasi'),
    (358, 'MAYBRAT', 'MARE SELATAN', 'SENI', 'BUM DESA FENYARURAN MANDIRI SENI', 'BUMKam', 'Nama Terverifikasi'),
    (359, 'MAYBRAT', 'MARE SELATAN', 'RENIS', 'BUM DESA MANDIRI RENIS', 'BUMKam', 'Nama Terverifikasi'),
    (360, 'MAYBRAT', 'MARE SELATAN', 'SIRE', 'BUM DESA SIRE MANDIRI SIRE', 'BUMKam', 'Nama Terverifikasi'),
    (361, 'MAYBRAT', 'MARE SELATAN', 'FASE', 'BUM DESA FASE FASE', 'BUMKam', 'Perbaikan Nama'),
    (362, 'MAYBRAT', 'MARE SELATAN', 'KURASO', 'BUM DESA SEHOBE JAYA KURASO', 'BUMKam', 'Nama Terverifikasi'),
    (363, 'MAYBRAT', 'MARE SELATAN', 'SIDI', 'BUM DESA MANDIRI SIDI', 'BUMKam', 'Nama Terverifikasi'),
    (364, 'MAYBRAT', 'MARE SELATAN', 'OSOM', 'BUM DESA UNARIT KAWAT OSOM', 'BUMKam', 'Nama Terverifikasi'),
    (365, 'MAYBRAT', 'MARE SELATAN', 'SIRE TIMUR', 'BUM DESA ALAM PAPUA SIRE TIMUR', 'BUMKam', 'Nama Terverifikasi'),
    (366, 'SORONG', 'MAYAMUK', 'WARMON KOKODA', 'BUM DESA BERSAMA SATU HATI MAYAMUK', 'BUMKam bersama', 'Dokumen Badan Hukum Terverifikasi'),
    (367, 'SORONG SELATAN', 'SAIFI', 'MLASWAT', 'BUM DESA BERSAMA KMPUNG MLASWAT', 'BUMKam bersama', 'Perbaikan Nama'),
    (368, 'RAJA AMPAT', 'SUPNIN', 'DUBER', 'BUM DESA BERSAMA TUNA JAYA BERSAMA', 'BUMKam bersama', 'Perbaikan Dokumen Badan Hukum'),
    (369, 'MAYBRAT', 'AIFAT', 'SAMPIKA', 'BUM DESA BERSAMA KUBE', 'BUMKam bersama', 'Perbaikan Nama'),
    (370, 'MAYBRAT', 'AIFAT', 'FRAWEBO', 'BUM DESA BERSAMA FRAWEBO RANA', 'BUMKam bersama', 'Perbaikan Nama'),
    (371, 'MAYBRAT', 'AIFAT', 'FRAWEBO', 'BUM DESA BERSAMA RANA FRAWEBO', 'BUMKam bersama', 'Perbaikan Nama'),
    (372, 'MAYBRAT', 'AIFAT UTARA', 'MOWES', 'BUM DESA BERSAMA CAMTOL', 'BUMKam bersama', 'Perbaikan Nama'),
    (373, 'MAYBRAT', 'AITINYO', 'SUMANIS', 'BUM DESA BERSAMA SUMANIS MANDIRI', 'BUMKam bersama', 'Perbaikan Nama'),
    (374, 'MAYBRAT', 'MARE', 'SUSWA', 'BUM DESA BERSAMA MARE MANDIRI', 'BUMKam bersama', 'Nama Terverifikasi'),
    (375, 'MAYBRAT', 'AYAMARU JAYA', 'TEMEL', 'BUM DESA BERSAMA USAHA EKONOMI', 'BUMKam bersama', 'Perbaikan Nama'),
    (376, 'MAYBRAT', 'AYAMARU SELATAN JAYA', 'ISNUM', 'BUM DESA BERSAMA ISNUM MANDIRI', 'BUMKam bersama', 'Perbaikan Nama'),
    (377, 'MAYBRAT', 'AYAMARU TENGAH', 'FIANE', 'BUM DESA BERSAMA TANI', 'BUMKam bersama', 'Perbaikan Nama'),
    (378, 'MAYBRAT', 'AYAMARU TENGAH', 'KARTAPURA', 'BUM DESA BERSAMA KAMESTUT   SEJAHTERA', 'BUMKam bersama', 'Dokumen Badan Hukum Terverifikasi'),
    (379, 'MAYBRAT', 'AYAMARU BARAT', 'SOROAN', 'BUM DESA BERSAMA AQUA WENSI JAYA', 'BUMKam bersama', 'Nama Terverifikasi'),
    (380, 'MAYBRAT', 'AYAMARU BARAT', 'SEHU', 'BUM DESA BERSAMA BUMDESA SEHU', 'BUMKam bersama', 'Perbaikan Nama'),
    (381, 'MAYBRAT', 'AITINYO TENGAH', 'WAY ''U''', 'BUM DESA BERSAMA ASIS JAYA', 'BUMKam bersama', 'Perbaikan Nama')
)
DELETE FROM bum_kampung target
USING source
WHERE target.tahun_anggaran = '2026'
  AND LOWER(target.kabupaten_kota) = LOWER(source.kabupaten_kota)
  AND LOWER(target.distrik) = LOWER(source.distrik)
  AND LOWER(target.kampung) = LOWER(source.kampung)
  AND LOWER(target.nama_bum_kampung) = LOWER(source.nama_bum_kampung);
